/**
 * The published-document promise.
 *
 * This app has shipped, so schema-v1 documents exist on real teachers' machines. Every
 * future model change has to carry them forward — a document saved by the published
 * build must keep opening, keep its content, and keep rendering.
 *
 * The corpus this reads (`src/test/corpus/v1-published.json`) is a **frozen artifact**,
 * regenerated by `scripts/emit-v1-corpus.test.ts` only when a *new* schema version is
 * cut. That freezing is the entire point: every other test in this repo round-trips a
 * worksheet that this build just constructed, which proves the build agrees with itself
 * and cannot detect a migration that quietly drops a field. Only a fixture written by
 * an older build can do that.
 *
 * When `CURRENT_SCHEMA_VERSION` is bumped, do **not** regenerate the v1 file. Add the
 * migration step, let these tests prove it carries the corpus across, and freeze a new
 * corpus for the new version beside it.
 */
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import v1Corpus from '@/test/corpus/v1-published.json';
import v2Corpus from '@/test/corpus/v2-published.json';
import graphV2 from '@/test/corpus/graph-v2.json';
import optionalCorpus from '@/test/corpus/v2-optional-sections.json';
import bankPaperCorpus from '@/test/corpus/bank-v0.6.0-paper.json';
import bankBankCorpus from '@/test/corpus/bank-v0.6.0-bank.json';
import { migrate, serializeWorksheet, CURRENT_SCHEMA_VERSION, isNewerThanBuild } from '@/model/migrations';
import { parseWorksheet, stringifyWorksheet } from '@/storage/document';
import { isGraphNewerThanBuild, migrateGraph, parseGraph, stringifyGraph } from '@/model/graph';
import { answerLayer } from '@/model/diagramAnswers';
import { computeNumbering } from '@/model/numbering';
import { sectionMarksById, worksheetMarks } from '@/model/marks';
import { renderWorksheet } from '@/render/worksheet';
import { resolveFlow } from '@/model/flow';
import { createMcqQuestion, createStructuredQuestion, createSubPart } from '@/model/factories';
import { copyQuestion } from '@/model/lineage';
import { parsePatternTag } from '@/model/patterns';
import { derivedTags, effectiveSlotTags, tagStateOf } from '@/model/tagSlots';
import { bi } from '@/model/text';
import type { McqQuestion, OutputMode, StructuredQuestion } from '@/model/types';

const MODE: OutputMode = { language: 'bilingual', version: 'student' };

/** Deep-count every `{en, zh}` pair carrying text, so "loads" can't mean "loads empty". */
function countText(value: unknown): number {
  if (Array.isArray(value)) return value.reduce<number>((sum, entry) => sum + countText(entry), 0);
  if (value && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    if (typeof record.text === 'string') return record.text.trim().length > 0 ? 1 : 0;
    return Object.values(record).reduce<number>((sum, entry) => sum + countText(entry), 0);
  }
  return 0;
}

describe('a document saved by the published build still opens', () => {
  it('loads without error and reports a version this build understands', () => {
    const worksheet = migrate(structuredClone(v1Corpus));

    expect(worksheet.schemaVersion).toBe(Math.max(CURRENT_SCHEMA_VERSION, 1));
    // Nothing was stashed as unrecognised: every key the corpus carries is a key this
    // build still knows (§ KNOWN_KEYS). A field that lands here is one that would
    // silently vanish from a real teacher's document on reload.
    expect(worksheet.__unknown).toBeUndefined();
  });

  it('keeps every structure the corpus was saved with', () => {
    const worksheet = migrate(structuredClone(v1Corpus));

    // The whole-document surface: losing any of these is losing a feature's data.
    expect(worksheet.cover).toBeDefined();
    expect(worksheet.pageFurniture).toBeDefined();
    expect(worksheet.footer?.bands.length).toBeGreaterThan(0);
    expect(worksheet.header).toBeDefined();
    expect(worksheet.baseFontSize).toBe(10);
    expect(worksheet.fonts).toBeDefined();
    expect(worksheet.pageSetup?.paper).toBe('A4');

    expect(worksheet.questions.length).toBe(v1Corpus.questions.length);
    expect(worksheet.layout.length).toBe(v1Corpus.layout.length);
    expect(worksheet.flow.length).toBe(v1Corpus.flow.length);
  });

  it('keeps the block kinds a question can hold', () => {
    const worksheet = migrate(structuredClone(v1Corpus));
    const kinds = new Set<string>();
    const walk = (value: unknown): void => {
      if (Array.isArray(value)) return value.forEach(walk);
      if (value && typeof value === 'object') {
        const record = value as Record<string, unknown>;
        if (typeof record.kind === 'string') kinds.add(record.kind);
        Object.values(record).forEach(walk);
      }
    };
    walk(worksheet.questions);

    // A diagram is stored geometry and an image is stored bytes; both are content a
    // teacher cannot recover if a migration drops them.
    expect(kinds).toContain('paragraph');
    expect(kinds).toContain('table');
    expect(kinds).toContain('image');
    expect(kinds).toContain('diagram');
  });

  it('keeps an unmarked sub-part unmarked (absent is not zero)', () => {
    const worksheet = migrate(structuredClone(v1Corpus));
    const structured = worksheet.questions.find(
      (question) => question.type === 'structured' && question.parts.some((part) => part.subParts),
    );
    const withSubs =
      structured?.type === 'structured'
        ? structured.parts.find((part) => part.subParts && part.subParts.length > 1)
        : undefined;

    expect(withSubs).toBeDefined();
    // The shared-marks shape: the first sub-part carries no marks at all. A migration
    // that defaults it to 0 would print a literal "(0 marks)" the teacher never wrote.
    expect(withSubs?.subParts?.[0].marks).toBeUndefined();
    expect(withSubs?.subParts?.[1].marks).toBe(5);
  });

  it('loses no authored text', () => {
    const before = countText(v1Corpus);
    const after = countText(migrate(structuredClone(v1Corpus)));

    expect(before).toBeGreaterThan(20);
    expect(after).toBe(before);
  });

  it('still renders, numbers and totals', () => {
    const worksheet = migrate(structuredClone(v1Corpus));

    // Loading is not enough — the document has to still be usable. These are the three
    // derivations everything downstream (preview, .docx, clipboard) is built on.
    expect(resolveFlow(worksheet).length).toBe(worksheet.flow.length);
    expect(worksheetMarks(worksheet)).toBeGreaterThan(0);

    // Every question still numbers, and the numbers reach the whole set — a document
    // whose flow survived but whose numbering did not is one that opens looking broken.
    const numbering = computeNumbering(worksheet);
    expect(numbering.questions.length).toBe(worksheet.questions.length);
    expect(numbering.byQuestionId.size).toBe(worksheet.questions.length);

    const rendered = renderWorksheet(worksheet, MODE);
    expect(rendered.items.length).toBeGreaterThan(0);
  });

  it('round-trips: loading and re-saving a published document changes nothing', () => {
    // The strongest form of the promise. An older document opened in a newer build and
    // saved again must come back out equivalent — this is what stops a reload from
    // quietly rewriting a teacher's file.
    const loaded = migrate(structuredClone(v1Corpus));
    const saved = serializeWorksheet(loaded);
    const reloaded = migrate(structuredClone(saved));

    expect(serializeWorksheet(reloaded)).toEqual(saved);
  });

  it('carries a paper target through load → save → load', () => {
    // An optional top-level field: without its KNOWN_KEYS entry it would land in
    // `__unknown` and vanish from the typed document on reload.
    const loaded = migrate(structuredClone(v1Corpus));
    expect(loaded.target).toBeUndefined();
    const target = { marks: 50, minutes: 60, counts: { mcq: 45 } };
    const reloaded = migrate(JSON.parse(JSON.stringify(serializeWorksheet({ ...loaded, target }))));
    expect(reloaded.__unknown).toBeUndefined();
    expect(reloaded.target).toEqual(target);
    expect({ ...reloaded, target: undefined }).toEqual({ ...loaded, target: undefined });
  });

  it('carries MCQ rationale and provenance through load → save → load', () => {
    // Question-level fields are not gated by KNOWN_KEYS; this proves `migrate` keeps them
    // on a published document, and adds none of its own to one that never had them.
    const loaded = migrate(structuredClone(v1Corpus));
    expect(JSON.stringify(loaded.questions)).not.toMatch(/"rationale"|"provenance"/);

    const question = createMcqQuestion();
    question.options[1] = { ...question.options[1], rationale: bi('Why B is right', 'B 為何正確') };
    question.provenance = bi('Modelled on DSE 2023 Q1', '改編自 2023 DSE 第 1 題');
    const edited = { ...loaded, questions: [...loaded.questions, question] };

    const reloaded = migrate(JSON.parse(JSON.stringify(serializeWorksheet(edited))));
    expect(reloaded.__unknown).toBeUndefined();
    expect(reloaded.questions.slice(0, -1)).toEqual(loaded.questions);
    const back = reloaded.questions[reloaded.questions.length - 1] as McqQuestion;
    expect(back.options[1].rationale).toEqual(question.options[1].rationale);
    expect(back.provenance).toEqual(question.provenance);
  });

  it('carries question lineage through load → save → load', () => {
    const loaded = migrate(structuredClone(v1Corpus));
    expect(JSON.stringify(loaded.questions)).not.toMatch(/"lineage"/);

    const question = copyQuestion(createMcqQuestion(), 'doc-source');
    const edited = { ...loaded, questions: [...loaded.questions, question] };

    const reloaded = migrate(JSON.parse(JSON.stringify(serializeWorksheet(edited))));
    expect(reloaded.__unknown).toBeUndefined();
    expect(reloaded.questions.slice(0, -1)).toEqual(loaded.questions);
    expect(reloaded.questions.at(-1)!.lineage).toEqual(question.lineage);
  });

  it('carries question tags through load → save → load', () => {
    const loaded = migrate(structuredClone(v1Corpus));
    expect(JSON.stringify(loaded.questions)).not.toMatch(/"tags"/);

    const question = { ...createMcqQuestion(), tags: ['C', 'C.ped', 'past paper'] };
    const edited = { ...loaded, questions: [...loaded.questions, question] };

    const reloaded = migrate(JSON.parse(JSON.stringify(serializeWorksheet(edited))));
    expect(reloaded.__unknown).toBeUndefined();
    expect(reloaded.questions.slice(0, -1)).toEqual(loaded.questions);
    expect(reloaded.questions.at(-1)!.tags).toEqual(['C', 'C.ped', 'past paper']);
  });

  it('carries a question’s tagsAt stamp through load → save → load', () => {
    // Question fields have no KNOWN_KEYS: `migrate` passes question objects through.
    const loaded = migrate(structuredClone(v1Corpus));
    const question = { ...createMcqQuestion(), tags: ['C.ped'], tagsAt: '2026-09-30T01:02:03.000Z' };
    const edited = { ...loaded, questions: [...loaded.questions, question] };

    const reloaded = migrate(JSON.parse(JSON.stringify(serializeWorksheet(edited))));
    expect(reloaded.__unknown).toBeUndefined();
    expect(reloaded.questions.slice(0, -1)).toEqual(loaded.questions);
    expect(reloaded.questions.at(-1)!.tagsAt).toBe('2026-09-30T01:02:03.000Z');
  });

  it('carries a 題型 (a reserved-form tag) through load → save → load, still readable', () => {
    const loaded = migrate(structuredClone(v1Corpus));
    const tags = ['C.ped', 'C.ped::Calculate PED from a change in TR', 'past paper'];
    const question = { ...createMcqQuestion(), tags };
    const edited = { ...loaded, questions: [...loaded.questions, question] };

    const reloaded = migrate(JSON.parse(JSON.stringify(serializeWorksheet(edited))));
    expect(reloaded.__unknown).toBeUndefined();
    expect(reloaded.questions.slice(0, -1)).toEqual(loaded.questions);
    expect(reloaded.questions.at(-1)!.tags).toEqual(tags);
    expect(parsePatternTag(reloaded.questions.at(-1)!.tags![1])).toEqual({ topic: 'C.ped', name: 'Calculate PED from a change in TR' });
  });

  it('carries part and sub-part topics and roots through load → save → load', () => {
    // Nested question fields have no KNOWN_KEYS either: `migrate` reads top-level keys only.
    const loaded = migrate(structuredClone(v1Corpus));
    expect(JSON.stringify(loaded.questions)).not.toMatch(/"rootId"|"tags"/);

    const question = copyQuestion(createStructuredQuestion(), 'doc-source');
    const sub = createSubPart();
    question.parts[0] = { ...question.parts[0], tags: ['C.ped', 'C.ped::Explain PED'], subParts: [{ ...sub, tags: ['D'], rootId: 'root-sub' }] };
    question.tags = ['mock 2025'];
    const edited = { ...loaded, questions: [...loaded.questions, question] };

    const reloaded = migrate(JSON.parse(JSON.stringify(serializeWorksheet(edited))));
    expect(reloaded.__unknown).toBeUndefined();
    expect(reloaded.questions.slice(0, -1)).toEqual(loaded.questions);
    const back = reloaded.questions.at(-1) as StructuredQuestion;
    expect(back.parts[0].tags).toEqual(['C.ped', 'C.ped::Explain PED']);
    expect(back.parts[0].rootId).toBe(question.parts[0].rootId);
    expect(back.parts[0].subParts![0]).toMatchObject({ tags: ['D'], rootId: 'root-sub' });
    expect(back.tags).toEqual(['mock 2025']);
  });

  it('keeps part topics and roots through v0.5.0’s duplicate, which spreads parts', () => {
    // v0.5.0's `withFreshIds` (src/store/worksheetStore.ts at the tag), verbatim in shape:
    // the released build a document with part fields may be opened and edited in.
    const v050Duplicate = (question: StructuredQuestion): StructuredQuestion => ({
      ...question,
      id: 'new-q',
      parts: question.parts.map((part, i) => ({
        ...part,
        id: `new-p${i}`,
        subParts: part.subParts?.map((sub, j) => ({ ...sub, id: `new-s${i}.${j}` })),
      })),
    });
    const question = copyQuestion(createStructuredQuestion(), 'doc-source');
    question.parts[0] = { ...question.parts[0], tags: ['C.ped'], subParts: [{ ...createSubPart(), tags: ['D'], rootId: 'root-sub' }] };
    const copy = v050Duplicate(question);
    expect(copy.parts[0]).toMatchObject({ tags: ['C.ped'], rootId: question.parts[0].rootId });
    expect(copy.parts[0].subParts![0]).toMatchObject({ tags: ['D'], rootId: 'root-sub' });
  });

  it('carries the bank fields (kind, classes, satOn, bankHidden) through load → save → load', () => {
    const loaded = migrate(structuredClone(v1Corpus));
    expect(loaded.kind).toBeUndefined();
    expect(loaded.classes).toBeUndefined();
    expect(loaded.satOn).toBeUndefined();
    expect(loaded.bankHidden).toBeUndefined();

    const fields = { kind: 'bank' as const, classes: ['5A', '5B'], satOn: '2025-11-03', bankHidden: true };
    const reloaded = migrate(JSON.parse(JSON.stringify(serializeWorksheet({ ...loaded, ...fields }))));
    expect(reloaded.__unknown).toBeUndefined();
    expect({ kind: reloaded.kind, classes: reloaded.classes, satOn: reloaded.satOn, bankHidden: reloaded.bankHidden }).toEqual(fields);
    expect({ ...reloaded, kind: undefined, classes: undefined, satOn: undefined, bankHidden: undefined }).toEqual(loaded);
  });
});

/** Every `answer: true` in a stored value, so "keeps the answer layer" cannot mean "keeps some". */
function countAnswers(value: unknown): number {
  if (Array.isArray(value)) return value.reduce<number>((sum, entry) => sum + countAnswers(entry), 0);
  if (value && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    return (record.answer === true ? 1 : 0) + Object.values(record).reduce<number>((sum, entry) => sum + countAnswers(entry), 0);
  }
  return 0;
}

describe('the v2 corpus: the answer layer and an answer key layout', () => {
  // `v2-published.json` / `graph-v2.json`: frozen, written once by
  // `scripts/emit-v2-corpus.test.ts`. v2 is written only when one of the two is used.
  it('the v1 corpus is still written at 1, byte for byte, so v0.5.0 keeps it editable', () => {
    const raw = readFileSync('src/test/corpus/v1-published.json', 'utf8');
    expect(serializeWorksheet(migrate(structuredClone(v1Corpus))).schemaVersion).toBe(1);
    expect(stringifyWorksheet(parseWorksheet(raw))).toBe(raw.trimEnd());
  });

  it('opens editable here, with nothing unrecognised', () => {
    const worksheet = migrate(structuredClone(v2Corpus));
    expect(v2Corpus.schemaVersion).toBe(2);
    expect(worksheet.schemaVersion).toBe(CURRENT_SCHEMA_VERSION);
    expect(isNewerThanBuild(worksheet)).toBe(false);
    expect(worksheet.__unknown).toBeUndefined();
  });

  it('keeps every answer flag, the key layout and all authored text', () => {
    const worksheet = migrate(structuredClone(v2Corpus));
    expect(countAnswers(v2Corpus)).toBe(14);
    expect(countAnswers(worksheet)).toBe(countAnswers(v2Corpus));
    expect(worksheet.answerKeyLayout).toEqual(v2Corpus.answerKeyLayout);
    expect(countText(worksheet)).toBe(countText(v2Corpus));
    expect(worksheet.questions.length).toBe(v2Corpus.questions.length);
    expect(worksheet.flow.length).toBe(v2Corpus.flow.length);
  });

  it('still leaves the answer layer out of the student version', () => {
    const worksheet = migrate(structuredClone(v2Corpus));
    const diagrams: Parameters<typeof answerLayer>[0][] = [];
    const walk = (value: unknown): void => {
      if (Array.isArray(value)) return value.forEach(walk);
      if (value && typeof value === 'object') {
        const record = value as Record<string, unknown>;
        if (record.kind === 'diagram') diagrams.push(record.diagram as Parameters<typeof answerLayer>[0]);
        Object.values(record).forEach(walk);
      }
    };
    walk(worksheet.questions);
    expect(diagrams.length).toBeGreaterThanOrEqual(3);
    expect(diagrams.filter((diagram) => answerLayer(diagram) !== null).length).toBe(3);
    expect(renderWorksheet(worksheet, MODE).items.length).toBeGreaterThan(0);
  });

  it('round-trips byte for byte, still written at 2', () => {
    const raw = readFileSync('src/test/corpus/v2-published.json', 'utf8');
    const saved = stringifyWorksheet(parseWorksheet(raw));
    expect(saved).toBe(raw.trimEnd());
    expect(JSON.parse(saved).schemaVersion).toBe(2);
  });

  it('the v2 graph opens editable, keeps its answers, and round-trips at 2', () => {
    const raw = readFileSync('src/test/corpus/graph-v2.json', 'utf8');
    const graph = migrateGraph(structuredClone(graphV2));
    expect(isGraphNewerThanBuild(graph)).toBe(false);
    expect(graph.__unknown).toBeUndefined();
    expect(countAnswers(graph)).toBe(countAnswers(graphV2));
    expect(countAnswers(graphV2)).toBe(6);
    expect(stringifyGraph(parseGraph(raw))).toBe(raw.trimEnd());
  });
});

describe('the v2 optional-sections corpus: answer any ONE, section targets, essay answers', () => {
  // `v2-optional-sections.json`: frozen, written once by
  // `scripts/emit-v2-optional-sections-corpus.test.ts`.
  const TEACHER: OutputMode = { language: 'en', version: 'teacher' };
  const STUDENT: OutputMode = { language: 'en', version: 'student' };
  const printed = (worksheet: ReturnType<typeof migrate>, mode: OutputMode) => JSON.stringify(renderWorksheet(worksheet, mode));

  it('opens editable here, with nothing unrecognised', () => {
    const worksheet = migrate(structuredClone(optionalCorpus));
    expect(optionalCorpus.schemaVersion).toBe(2);
    expect(isNewerThanBuild(worksheet)).toBe(false);
    expect(worksheet.__unknown).toBeUndefined();
  });

  it('keeps the section settings, both essays’ answers and schemes, topics and all text', () => {
    const worksheet = migrate(structuredClone(optionalCorpus));
    const sections = worksheet.layout.filter((element) => element.kind === 'section');
    expect(sections.map((s) => [s.answerCount, s.targetMarks])).toEqual([
      [undefined, undefined],
      [undefined, 8],
      [1, 12],
    ]);
    const essays = worksheet.questions.filter((q) => (q as StructuredQuestion).parts.length === 0) as StructuredQuestion[];
    expect(essays).toHaveLength(2);
    for (const essay of essays) {
      expect(essay.answer).toBeDefined();
      expect(essay.scheme?.levels).toHaveLength(2);
    }
    const tagged = worksheet.questions.find((q) => q.tags) as StructuredQuestion;
    expect(tagged.tags).toEqual(['E', 'mock 2026']);
    expect(tagged.parts[0].tags).toEqual(['E.monopoly']);
    expect(tagged.lineage?.fromDocId).toBe('doc-taxi');
    expect(countText(worksheet)).toBe(countText(optionalCorpus));
  });

  it('totals the best ONE essay, and prints each essay’s answer for the teacher only', () => {
    const worksheet = migrate(structuredClone(optionalCorpus));
    expect([...sectionMarksById(worksheet).values()]).toEqual([6, 8, 12]);
    expect(worksheetMarks(worksheet)).toBe(26);
    expect(printed(worksheet, TEACHER)).toContain('Raises wages of those employed');
    expect(printed(worksheet, TEACHER)).toContain('Balanced discussion');
    expect(printed(worksheet, STUDENT)).not.toContain('Raises wages of those employed');
    expect(printed(worksheet, STUDENT)).not.toContain('Balanced discussion');
  });

  it('round-trips byte for byte, still written at 2', () => {
    const raw = readFileSync('src/test/corpus/v2-optional-sections.json', 'utf8');
    const saved = stringifyWorksheet(parseWorksheet(raw));
    expect(saved).toBe(raw.trimEnd());
    expect(JSON.parse(saved).schemaVersion).toBe(2);
  });
});

describe('the v0.6.0 bank corpus: part tags, part roots, a copy pair and the legacy shape', () => {
  // `bank-v0.6.0-paper.json` / `bank-v0.6.0-bank.json`: frozen, written once by the v0.6.0
  // release itself (`scripts/emit-bank-v0.6.0-corpus.test.ts` refuses any other commit).
  // The storage index and bank index rows beside them: `legacyIndex` and `bankCorpus` tests.
  const FILES = [
    ['src/test/corpus/bank-v0.6.0-paper.json', bankPaperCorpus],
    ['src/test/corpus/bank-v0.6.0-bank.json', bankBankCorpus],
  ] as const;
  const paper = () => migrate(structuredClone(bankPaperCorpus));
  const bank = () => migrate(structuredClone(bankBankCorpus));
  const parted = (worksheet: ReturnType<typeof migrate>, id: string) =>
    worksheet.questions.find((q) => q.id === id) as StructuredQuestion;
  const roots = (q: StructuredQuestion) => [
    q.lineage?.rootId,
    ...q.parts.flatMap((part) => [part.rootId, ...(part.subParts ?? []).map((sub) => sub.rootId)]),
  ];

  it('both documents open editable here, with nothing unrecognised and all text', () => {
    for (const [, corpus] of FILES) {
      const worksheet = migrate(structuredClone(corpus));
      expect(corpus.schemaVersion).toBe(1);
      expect(isNewerThanBuild(worksheet)).toBe(false);
      expect(worksheet.__unknown).toBeUndefined();
      expect(countText(worksheet)).toBe(countText(corpus));
      expect(worksheet.questions.length).toBe(corpus.questions.length);
    }
    expect(bank().kind).toBe('bank');
    expect(paper().kind).toBeUndefined();
    expect([paper().classes, paper().satOn]).toEqual([['5A', '5B'], '2026-10-02']);
  });

  it('keeps part lists, a sub-part’s own list, every part root and free tags on the question', () => {
    const question = parted(paper(), 'v060-030');
    expect(question.tags).toEqual(['mock 2026']);
    expect(question.tagsAt).toBe('2026-10-04T08:00:00.000Z');
    expect(question.lineage).toEqual({ rootId: 'v060-013', fromDocId: 'bank-v060-earlier-paper', copiedAt: '2026-10-04T08:00:00.000Z' });
    const [a, b] = question.parts;
    expect([a.rootId, a.tags]).toEqual(['v060-018', ['C.ped', 'C.ped::Explain PED']]);
    expect([b.rootId, b.tags]).toEqual(['v060-021', ['C.intervention']]);
    expect(b.subParts?.map((sub) => [sub.rootId, sub.tags])).toEqual([
      ['v060-024', undefined],
      ['v060-027', ['E.efficiency']],
    ]);
    // What they mean is unchanged too: (b)(i) inherits (b), (b)(ii) replaces it.
    expect(Object.fromEntries(effectiveSlotTags(tagStateOf(question)))).toEqual({
      'v060-018': ['C.ped', 'C.ped::Explain PED'],
      'v060-021': ['C.intervention'],
      'v060-024': ['C.intervention'],
      'v060-027': ['E.efficiency'],
    });
  });

  it('keeps the copy pair: one root, and the same part and sub-part roots in both documents', () => {
    const inPaper = parted(paper(), 'v060-030');
    const inBank = parted(bank(), 'v060-062');
    expect(roots(inPaper)).toEqual(['v060-013', 'v060-018', 'v060-021', 'v060-024', 'v060-027']);
    expect(roots(inBank)).toEqual(roots(inPaper));
    expect(tagStateOf(inBank)).toEqual(tagStateOf(inPaper));
    expect(inBank.lineage).toEqual({ rootId: 'v060-013', fromDocId: 'bank-v060-paper', copiedAt: '2026-10-04T09:30:00.000Z' });
    const mcq = bank().questions.find((q) => q.type === 'mcq')!;
    expect([mcq.lineage?.rootId, mcq.tags]).toEqual(['v060-006', ['C.intervention', 'mock 2026']]);
  });

  it('keeps the legacy shape: topics on the whole of a question with parts, as loaded', () => {
    const legacy = parted(paper(), 'v060-040');
    expect(legacy.tags).toEqual(['C.equilibrium', 'mock 2026']);
    expect(legacy.parts.map((part) => [part.rootId, part.tags])).toEqual([[undefined, undefined]]);
    // Still every untagged part's default; opening never moves it onto the part.
    expect(Object.fromEntries(effectiveSlotTags(tagStateOf(legacy)))).toEqual({ 'v060-042': ['C.equilibrium'] });
    expect(derivedTags(legacy)).toEqual(['C.equilibrium', 'mock 2026']);
  });

  it('round-trips byte for byte, still written at 1', () => {
    for (const [path] of FILES) {
      const raw = readFileSync(path, 'utf8');
      const saved = stringifyWorksheet(parseWorksheet(raw));
      expect(saved).toBe(raw.trimEnd());
      expect(JSON.parse(saved).schemaVersion).toBe(1);
    }
  });
});
