/**
 * The published-document promise.
 *
 * This app has shipped, so schema-v1 documents exist on real teachers' machines. Every
 * future model change has to carry them forward — a document saved by the published
 * build must keep opening, keep its content, and keep rendering.
 *
 * The corpus this reads (`src/test/corpus/v1-published.json`) is a **frozen artifact**,
 * regenerated by `scripts/emit-v1-corpus.test.ts` only when a *new* schema version is
 * cut. That freezing is the entire point: every other test in this repo round-trips a
 * worksheet that this build just constructed, which proves the build agrees with itself
 * and cannot detect a migration that quietly drops a field. Only a fixture written by
 * an older build can do that.
 *
 * When `CURRENT_SCHEMA_VERSION` is bumped, do **not** regenerate the v1 file. Add the
 * migration step, let these tests prove it carries the corpus across, and freeze a new
 * corpus for the new version beside it.
 */
import { describe, expect, it } from 'vitest';
import v1Corpus from '@/test/corpus/v1-published.json';
import { migrate, serializeWorksheet, CURRENT_SCHEMA_VERSION } from '@/model/migrations';
import { computeNumbering } from '@/model/numbering';
import { worksheetMarks } from '@/model/marks';
import { renderWorksheet } from '@/render/worksheet';
import { resolveFlow } from '@/model/flow';
import type { OutputMode } from '@/model/types';

const MODE: OutputMode = { language: 'bilingual', version: 'student' };

/** Deep-count every `{en, zh}` pair carrying text, so "loads" can't mean "loads empty". */
function countText(value: unknown): number {
  if (Array.isArray(value)) return value.reduce<number>((sum, entry) => sum + countText(entry), 0);
  if (value && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    if (typeof record.text === 'string') return record.text.trim().length > 0 ? 1 : 0;
    return Object.values(record).reduce<number>((sum, entry) => sum + countText(entry), 0);
  }
  return 0;
}

describe('a document saved by the published build still opens', () => {
  it('loads without error and reports a version this build understands', () => {
    const worksheet = migrate(structuredClone(v1Corpus));

    expect(worksheet.schemaVersion).toBe(Math.max(CURRENT_SCHEMA_VERSION, 1));
    // Nothing was stashed as unrecognised: every key the corpus carries is a key this
    // build still knows (§ KNOWN_KEYS). A field that lands here is one that would
    // silently vanish from a real teacher's document on reload.
    expect(worksheet.__unknown).toBeUndefined();
  });

  it('keeps every structure the corpus was saved with', () => {
    const worksheet = migrate(structuredClone(v1Corpus));

    // The whole-document surface: losing any of these is losing a feature's data.
    expect(worksheet.cover).toBeDefined();
    expect(worksheet.pageFurniture).toBeDefined();
    expect(worksheet.footer?.bands.length).toBeGreaterThan(0);
    expect(worksheet.header).toBeDefined();
    expect(worksheet.baseFontSize).toBe(10);
    expect(worksheet.fonts).toBeDefined();
    expect(worksheet.pageSetup?.paper).toBe('A4');

    expect(worksheet.questions.length).toBe(v1Corpus.questions.length);
    expect(worksheet.layout.length).toBe(v1Corpus.layout.length);
    expect(worksheet.flow.length).toBe(v1Corpus.flow.length);
  });

  it('keeps the block kinds a question can hold', () => {
    const worksheet = migrate(structuredClone(v1Corpus));
    const kinds = new Set<string>();
    const walk = (value: unknown): void => {
      if (Array.isArray(value)) return value.forEach(walk);
      if (value && typeof value === 'object') {
        const record = value as Record<string, unknown>;
        if (typeof record.kind === 'string') kinds.add(record.kind);
        Object.values(record).forEach(walk);
      }
    };
    walk(worksheet.questions);

    // A diagram is stored geometry and an image is stored bytes; both are content a
    // teacher cannot recover if a migration drops them.
    expect(kinds).toContain('paragraph');
    expect(kinds).toContain('table');
    expect(kinds).toContain('image');
    expect(kinds).toContain('diagram');
  });

  it('keeps an unmarked sub-part unmarked (absent is not zero)', () => {
    const worksheet = migrate(structuredClone(v1Corpus));
    const structured = worksheet.questions.find(
      (question) => question.type === 'structured' && question.parts.some((part) => part.subParts),
    );
    const withSubs =
      structured?.type === 'structured'
        ? structured.parts.find((part) => part.subParts && part.subParts.length > 1)
        : undefined;

    expect(withSubs).toBeDefined();
    // The shared-marks shape: the first sub-part carries no marks at all. A migration
    // that defaults it to 0 would print a literal "(0 marks)" the teacher never wrote.
    expect(withSubs?.subParts?.[0].marks).toBeUndefined();
    expect(withSubs?.subParts?.[1].marks).toBe(5);
  });

  it('loses no authored text', () => {
    const before = countText(v1Corpus);
    const after = countText(migrate(structuredClone(v1Corpus)));

    expect(before).toBeGreaterThan(20);
    expect(after).toBe(before);
  });

  it('still renders, numbers and totals', () => {
    const worksheet = migrate(structuredClone(v1Corpus));

    // Loading is not enough — the document has to still be usable. These are the three
    // derivations everything downstream (preview, .docx, clipboard) is built on.
    expect(resolveFlow(worksheet).length).toBe(worksheet.flow.length);
    expect(worksheetMarks(worksheet)).toBeGreaterThan(0);

    // Every question still numbers, and the numbers reach the whole set — a document
    // whose flow survived but whose numbering did not is one that opens looking broken.
    const numbering = computeNumbering(worksheet);
    expect(numbering.questions.length).toBe(worksheet.questions.length);
    expect(numbering.byQuestionId.size).toBe(worksheet.questions.length);

    const rendered = renderWorksheet(worksheet, MODE);
    expect(rendered.items.length).toBeGreaterThan(0);
  });

  it('round-trips: loading and re-saving a published document changes nothing', () => {
    // The strongest form of the promise. An older document opened in a newer build and
    // saved again must come back out equivalent — this is what stops a reload from
    // quietly rewriting a teacher's file.
    const loaded = migrate(structuredClone(v1Corpus));
    const saved = serializeWorksheet(loaded);
    const reloaded = migrate(structuredClone(saved));

    expect(serializeWorksheet(reloaded)).toEqual(saved);
  });
});
